In [43]:
#Nama   : Muhammad Farras Ibnu Budiyanto
#Nim    : 240401010085
#Kelas  : IF404

#=========================
#STRUKTUR DATA PYTHON
#=========================
# Membuat list dengan []
print("Membuat List")
data = [10, 20, 30, 40, 50, True]
print(data[0]) # data dari paling depan
print(data[-1]) #  data dari paling belakang
print(data[1:3]) # data antara ke 2 dan 4, namun data ke-4 tidak diajak
# Manipulasi
data.append(99) # tambah data diakhir
data.insert(1, 55) # sisipkan data di posisi 1
data.remove(20) # hapus nilai sesuai yang diinginkan '20'
data.sort() #mengurutkan data jika tipe sama
print(data)

# membuat Tuple dengan ()
#Tuple tidak bisa diubah, jadi cocok untuk data yang tidak berubah
print("\nMembuat Tuple")
koordinat_kampus = (2026.15, 2024.25, 'Depok')
print(koordinat_kampus[0])
x, y, kota = koordinat_kampus
print(x, y, kota)

# membuat Dictionary dengan {}
print("\nMembuat Dictionary")
mahasiswa = {
    'nama':'Farras',
    'nim':'240401010085',
    'prodi': 'Teknik Informatika',
    'kelas': 'IF404'
    }
# Akses nilai
print(mahasiswa['nama']) # menampilkan nilai 'nama'
print(mahasiswa.get('usia', 20)) # menambah default jika key tidak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # menambah key baru
del mahasiswa['nim']  #menghapus key yang sudah ada
#Implementasi
print(mahasiswa)


#Membuat Set dengan {}
print("\nMembuat set")
kota_a = {'Jakarta','Bandung','Depok'}
kota_b = {'Bandung','Pasuruan','Bali'}
print(kota_a & kota_b) # intersect (mengambil nilai yang sama dari kedua data tersebut)
print(kota_a | kota_b) # union (Mengambil semua nilai dari data, namun untuk data yang sama cukup ditulis sekali)
print(kota_a - kota_b) # difference (Mengambil nilai dari kota a, namun jika ada data yang sama di kota b maka akan dibuang)

#============================
#NUMPY DAN KOMPUTASI NUMERIK
#============================
import numpy as np
print("\nMembuat NumPy array")
Array_1D = np.array ([2, 3, 4]) #Array 1 dimensi terdiri dari 1 baris dan 1 kolom
Array_2D = np.array ([[2,3,4], [5,6,7]]) #array 2 dimensi yang terdiri dari 2 garis dan 2 kolom
print("=== HASIL ARRAY UTAMA ===")
print("Array_1D :", Array_1D)
print("Array_2D :\n", Array_2D)

# Array khusus
print("\nMembuat array khusus")
zero = np.zeros((3, 4)) # membuat matriks zero dengan (Baris, Kolom)
one = np.ones((2, 3)) # membuat matriks 1 dengan (Baris, kolom)
eye = np.eye(3) # membuat matriks identitas dengan (baris dan kolom)
print("Array zero:\n", zero)
print("Array one:\n", one)
print("Array eye:\n", eye)

#sequence
print("\nMembuat sequence")
arange = np.arange(0, 20, 2) # membuat barisan aritmetika (data dimulai, batas data, beda data)
linsp = np.linspace(0, 1, 6) # menebar ke 12 titik secara merata
print("Array arange:\n", arange)
print("Array linsp:\n", linsp)

# Array acak
rng = np.random.default_rng(30) #mengaktifkan mesin pembuat acak dengan kata kunci 30
x = rng.integers(0, 100, (3,3)) # meminta bilangan bulat dari (0 sampai 100, (Garis, kolom))
print("Array acak:\n", x)
print("Array rng:\n", np.random.default_rng(30))

#operasi vektosisasi dan fungsi statistik
vektor_a = np.array ([10,9,8,7,6])
vektor_b = np.array ([1,2,3,4,5])
print("\nOperasi Vektor")
print(vektor_a + vektor_b) #Pertambahan
print(vektor_a - vektor_b) #pengurangan
print(vektor_a * vektor_b) #Perkalian
print("\nAkar kuadrat:")
print(np.sqrt(vektor_a))
print("\nExponen:")
print(np.exp(vektor_b))
print("\nLogaritma")
print(np.log(vektor_b))

# Fungsi statistik
print("\nFungsi statistik lengkap")
data = ([4,6,8,10,12,14,16,18,20])
print(f'Mean: {np.mean(data):.4f}') # rata-rata
print(f'Std: {np.std(data):.4f}') #devaluasi
print(f'Min: {np.min(data):.4f}') #Nilai minimal
print(f'Max: {np.max(data):.4f}') #Nilai Maksimal
print(f'Q1: {np.percentile(data,25):.4f}') #nilai quartil 1
print(f'Q3: {np.percentile(data,75):.4f}') #nilai quartil 3

#===================================
#PANDAS VARIABEL DAN SERIES
#===================================
import pandas as pd

#series array 1d
print("\nMembuat array 1 dimensi berlabel")
umur = pd.Series([14, 19, 20, 22],
index=['Fathinah','Faiz','Farras','Faiq'])
print(umur['Faiq']) # mengambil nilai umur dari indexs 'Faiq'
print(umur.mean()) # mengambil nilai rata-rata
print(umur[umur > 18]) # memfilter nilai

#Membuat Dataframe dari dictionary
print("\nMembuat array 2 dimensi berlabel")
data = {'Nama': ['Farras', 'Nabil', 'Hammam'],
        'Umur': ['20', '21', '22'],
        'Kota': ['Depok', 'Balikpapan', 'Karawang']
}
df = pd.DataFrame(data)
print(df.shape) # menampilkan (baris,kolom)/(3,3)
print(df.dtypes) # menjelaskan tipe data per kolom
print(df.columns) # menampilkan nama-nama kolom


#============================
#BOOLEAN INDEXING
#============================

print("\nMenganalisis data dengan metode boolean indexing")
# Memuat dari file lokal
#contohnya df = pd.read_csv('data/penjualan.csv')
# Memuat dari URL (dataset publik)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("\n Memuat 5 baris pertama")
display (df.head(5)) # untuk memunculkan data teratas terserah mau berapa pun
print("\nTipe data dan missin")
df.info() # untuk menunjukkan tipe data dan missing values
df.describe() # statistik deskriptif

df = pd.read_csv(url)
# Filter satu kondisi
print("\nCara memfilter data dengan 1 kondisi")
penumpang_selamat = df[df['Survived'] == 1]
print("Jumlah penumpang yang selamat", len(penumpang_selamat))
penumpang_wanita = df[df['Sex'] == 'female']
print("Jumlah penumpang wanita", len(penumpang_wanita))
# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') &
(df['Pclass']==1)]
# Seleksi kolom tertentu
print("\nMenyeleksi data berdasarkan kolom tertentu")
df[['Name','Age','Sex','Survived']]

#==================================
#GROUPBY DAN AGREGASI
#==================================
print("\nMemilih data secara Groupby")
print("\ndf.groupby (kolom yang ingin dikelompokkan)[data yang ingin diambil nilainya].mean()")
hasil_Groupby = df.groupby('Pclass')['Survived'].mean()
print(hasil_Groupby)

# Agregasi multiple kolom & fungsi
print("\nAgregasi multiple kolom & fungsi")
hasil = df.groupby('Pclass').agg(
total = ('PassengerId', 'count'),
selamat = ('Survived', 'sum'),
pct_selamat= ('Survived', 'mean'),
rata_usia = ('Age', 'mean'),
max_fare = ('Fare', 'max')
)
hasil = hasil.round(3)
print(hasil)

# GroupBy multi-kolom
print("\nGroupby multi-kolom")
df.groupby(['Pclass','Sex'])['Survived']\
.mean().unstack().round(3)

Membuat List
10
True
[20, 30]
[True, 10, 30, 40, 50, 55, 99]

Membuat Tuple
2026.15
2026.15 2024.25 Depok

Membuat Dictionary
Farras
20
{'nama': 'Farras', 'prodi': 'Teknik Informatika', 'kelas': 'IF404', 'angkatan': 2024}

Membuat set
{'Bandung'}
{'Depok', 'Pasuruan', 'Bali', 'Bandung', 'Jakarta'}
{'Depok', 'Jakarta'}

Membuat NumPy array
=== HASIL ARRAY UTAMA ===
Array_1D : [2 3 4]
Array_2D :
 [[2 3 4]
 [5 6 7]]

Membuat array khusus
Array zero:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array one:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Membuat sequence
Array arange:
 [ 0  2  4  6  8 10 12 14 16 18]
Array linsp:
 [0.  0.2 0.4 0.6 0.8 1. ]
Array acak:
 [[10 23 75]
 [42 39  9]
 [63 59 24]]
Array rng:
 Generator(PCG64)

Operasi Vektor
[11 11 11 11 11]
[9 7 5 3 1]
[10 18 24 28 30]

Akar kuadrat:
[3.16227766 3.         2.82842712 2.64575131 2.44948974]

Exponen:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Logaritma
[0.         0.69314718 1.09861229 1.38629436 1.60943791]

Fungsi statistik lengkap
Mean: 12.0000
Std: 5.1640
Min: 4.0000
Max: 20.0000
Q1: 8.0000
Q3: 16.0000

Membuat array 1 dimensi berlabel
22
18.75
Faiz      19
Farras    20
Faiq      22
dtype: int64

Membuat array 2 dimensi berlabel
(3, 3)
Nama    object
Umur    object
Kota    object
dtype: object
Index(['Nama', 'Umur', 'Kota'], dtype='object')

Menganalisis data dengan metode boolean indexing

 Memuat 5 baris pertama

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Tipe data dan missin
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Cara memfilter data dengan 1 kondisi
Jumlah penumpang yang selamat 342
Jumlah penumpang wanita 314

Menyeleksi data berdasarkan kolom tertentu

Memilih data secara Groupby

df.groupby (kolom yang ingin dikelompokkan)[data yang ingin diambil nilainya].mean()
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Agregasi multiple kolom & fungsi
        total  selamat  pct_selamat  rata_usia  max_fare
Pclass
1         216      136        0.630     38.233   512.329
2         184       87        0.473     29.878    73.500
3         491      119        0.242     25.141    69.550

Groupby multi-kolom

Sex     female   male
Pclass
1        0.968  0.369
2        0.921  0.157
3        0.500  0.135

In [46]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q1
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
print("=== TAMPILAN TABEL TITANIC ===")
display(df)

# 3. df.shape untuk tahu total baris & kolom, df.columns.tolist() untuk ngelist nama kolomnya
print("\n=== JAWABAN SOAL Q1 ===")
print("Ukuran Dataset (Baris, Kolom):", df.shape)
print("\nNama-nama kolom yang tersedia:")
print(df.columns.tolist())

#Menggunakan tolist agar data tersusun rapih

=== TAMPILAN TABEL TITANIC ===

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

=== JAWABAN SOAL Q1 ===
Ukuran Dataset (Baris, Kolom): (891, 12)

Nama-nama kolom yang tersedia:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [51]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q2
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
display(df)

# .isnull().sum() akan menghitung berapa total baris yang kosong di tiap kolom
print("\n=== 1. DATA KOSONG ===")
data_kosong = df.isnull().sum()
print(data_kosong)

print("\n=== 2. PERSENTASE DATA KOSONG (BIAR LEBIH SPESIFIK) ===")
# Menghitung persentase data bolong: (jumlah kosong / total seluruh baris) * 100
persen_kosong = (df.isnull().sum() / len(df)) * 100
print(persen_kosong.round(2).astype(str) + ' %')

# df.isnull().sum() digunkan untuk mencari jumlah nilai kosong
# menggunakan operasi jumlah data bolong/jumlah baris * 100 untuk mencari rata-rata
# .round(2) digunakan untuk nilai desimal cukup membawa 2 nilai (3.14), dan astype(str) agar data dalam bentuk angka bisa digabung dengan data string

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

=== 1. DATA KOSONG ===
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

=== 2. PERSENTASE DATA KOSONG (BIAR LEBIH SPESIFIK) ===
PassengerId      0.0 %
Survived         0.0 %
Pclass           0.0 %
Name             0.0 %
Sex              0.0 %
Age            19.87 %
SibSp            0.0 %
Parch            0.0 %
Ticket           0.0 %
Fare             0.0 %
Cabin           77.1 %
Embarked        0.22 %
dtype: object

In [56]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q3
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
display(df)

print("\nPenumpang yang selamat")
penumpang = df['Survived'].mean() *100
print (penumpang.round(2).astype(str) + ' %')

#mengambil rata-rata orang yang selamat dengan .mean()
# menggunakan operasi jumlah orang yang selamat * 100 untuk mencari rata-rata
# .round(2) digunakan untuk nilai desimal cukup membawa 2 nilai (3.14), dan astype(str) agar data dalam bentuk angka bisa digabung dengan data string

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Penumpang yang selamat
38.38 %

In [69]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q4
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
display(df)

print("\nRata-rata usia wanita class 1")
Jumlah_wanita = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]
rata_usia = Jumlah_wanita['Age'].mean()
print(rata_usia.round(2).astype(str)  + ' tahun')

# menggunakan operasi rata-rata jumlah wanita (umurnya saja)
# .round(2) digunakan untuk nilai desimal cukup membawa 2 nilai (3.14), dan astype(str) agar data dalam bentuk angka bisa digabung dengan data string

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Rata-rata usia wanita class 1
34.61 tahun

In [70]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q5
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
display(df)

print("Tingkat keselamatan perkelas dalam persen")
Tingkat_Keselamatan = df.groupby('Pclass')['Survived'].mean() * 100
print(Tingkat_Keselamatan.round(2).astype(str) + ' %')

# menggunakan operasi jumlah rata-rata tingkat keselamatan * 100 untuk mencari rata-rata dalam persen
# .round(2) digunakan untuk nilai desimal cukup membawa 2 nilai (3.14), dan astype(str) agar data dalam bentuk angka bisa digabung dengan data string

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Tingkat keselamatan perkelas dalam persen
Pclass
1    62.96 %
2    47.28 %
3    24.24 %
Name: Survived, dtype: object

In [73]:
# =======================================================
# MEMUAT DATASET TITANIC DAN MENJAWAB Q6
# =======================================================
import numpy as np
import pandas as pd

# 1. pd.read_csv() fungsinya untuk membaca file tabel/csv dari link internet
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
display(df)

anak_anak = df[df['Age'] < 12]
anak_selamat = anak_anak['Survived'].mean() * 100
print("\nTingkat keselamatan anak-anak dalam persen")
print(anak_selamat.round(2).astype(str) + ' %')

#menkategorikan anak-anak untuk penumpang dengan usia  < 12
#mencari tingkat keselamatan penumpang yang tergolong anak-anak dalam persen
# menggunakan operasi rata-rata keselamatan untuk penumpang kategori anak * 100 untuk mencari rata-rata
# .round(2) digunakan untuk nilai desimal cukup membawa 2 nilai (3.14), dan astype(str) agar data dalam bentuk angka bisa digabung dengan data string

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Tingkat keselamatan anak-anak dalam persen
57.35 %